description: >
    Golang docker executor
docker:
    - image: "cimg/go:<<parameters.tag>>"
      auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
parameters:
    tag:
        default: "1.16.5"
        description: >
            Pick a specific cimg/python image variant:
            https://hub.docker.com/r/cimg/python/tags
        type: string
